-- MySQL Script generated by MySQL Workbench
-- Tue Nov 29 14:25:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MOP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MOP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MOP` DEFAULT CHARACTER SET utf8 ;
USE `MOP` ;

-- -----------------------------------------------------
-- Table `MOP`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MOP`.`Proveedor` (
  `idProveedor` INT NOT NULL,
  `rut_proveedor` VARCHAR(45) NOT NULL,
  `nombre_proveedor` VARCHAR(45) NOT NULL,
  `telefono_proveedor` VARCHAR(45) NOT NULL,
  `direccion_proveedor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProveedor`));


-- -----------------------------------------------------
-- Table `MOP`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MOP`.`Factura` (
  `idFactura` INT NOT NULL,
  `nro_factura` VARCHAR(45) NOT NULL,
  `cantidad` INT NOT NULL,
  `fecha_factura` DATE NOT NULL,
  `proveedor_id` INT NOT NULL,
  PRIMARY KEY (`idFactura`),
  CONSTRAINT `proveedor_id`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `MOP`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `proveedor_id_idx` ON `MOP`.`Factura` (`proveedor_id` ASC);


-- -----------------------------------------------------
-- Table `MOP`.`Perfil_bodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MOP`.`Perfil_bodega` (
  `idPerfil_bodega` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPerfil_bodega`));


-- -----------------------------------------------------
-- Table `MOP`.`Tipo_medida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MOP`.`Tipo_medida` (
  `idTipo_medida` INT NOT NULL,
  `descripcion_medida` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo_medida`));


-- -----------------------------------------------------
-- Table `MOP`.`Perfil_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MOP`.`Perfil_usuario` (
  `idPerfil_usuario` INT NOT NULL,
  `descripcion_perfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPerfil_usuario`));


-- -----------------------------------------------------
-- Table `MOP`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MOP`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `contrasenha` INT NOT NULL,
  `perfil_id` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `perfil_id`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `MOP`.`Perfil_usuario` (`idPerfil_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `perfil_id_idx` ON `MOP`.`Usuario` (`perfil_id` ASC);


-- -----------------------------------------------------
-- Table `MOP`.`Bodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MOP`.`Bodega` (
  `idBodega` INT NOT NULL,
  `nombre_bodega` VARCHAR(45) NOT NULL,
  `direccion_bodega` VARCHAR(45) NOT NULL,
  `stock` INT NOT NULL,
  `stock_min` INT NOT NULL,
  `perfil_bodega_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`idBodega`),
  CONSTRAINT `perfil_bodega_id`
    FOREIGN KEY (`perfil_bodega_id`)
    REFERENCES `MOP`.`Perfil_bodega` (`idPerfil_bodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `MOP`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `usuario_id_idx` ON `MOP`.`Bodega` (`usuario_id` ASC);

CREATE INDEX `perfil_bodega_id_idx` ON `MOP`.`Bodega` (`perfil_bodega_id` ASC);


-- -----------------------------------------------------
-- Table `MOP`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MOP`.`Producto` (
  `idProducto` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `fecha_ingreso` VARCHAR(45) NOT NULL,
  `tipo_medida_id` INT NOT NULL,
  `factura_id` INT NOT NULL,
  `bodega_id` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  CONSTRAINT `tipo_medida_id`
    FOREIGN KEY (`tipo_medida_id`)
    REFERENCES `MOP`.`Tipo_medida` (`idTipo_medida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `factura_id`
    FOREIGN KEY (`factura_id`)
    REFERENCES `MOP`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bodega_id`
    FOREIGN KEY (`bodega_id`)
    REFERENCES `MOP`.`Bodega` (`idBodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `tipo_medida_id_idx` ON `MOP`.`Producto` (`tipo_medida_id` ASC);

CREATE INDEX `factura_id_idx` ON `MOP`.`Producto` (`factura_id` ASC);

CREATE INDEX `bodega_id_idx` ON `MOP`.`Producto` (`bodega_id` ASC);


-- -----------------------------------------------------
-- Table `MOP`.`Medida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MOP`.`Medidor` (
  `idMedida` INT NOT NULL,
  `descripcion_medidor` VARCHAR(45) NOT NULL,
  `tipo_medida_id` INT NOT NULL,
  PRIMARY KEY (`idMedidor`),
  CONSTRAINT `tipo_medida_id`
    FOREIGN KEY (`tipo_medida_id`)
    REFERENCES `MOP`.`Tipo_medida` (`idTipo_medida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `tipo_medida_id_idx` ON `MOP`.`Medida` (`tipo_medida_id` ASC);


-- -----------------------------------------------------
-- Table `MOP`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MOP`.`Provincia` (
  `idProvincia` INT NOT NULL,
  `nombre_provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProvincia`));


-- -----------------------------------------------------
-- Table `MOP`.`Solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MOP`.`Solicitud` (
  `idSolicitud` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `rut_solicitante` VARCHAR(45) NOT NULL,
  `cantidad_solicitada` VARCHAR(45) NOT NULL,
  `provincia_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  PRIMARY KEY (`idSolicitud`),
  CONSTRAINT `provincia_id`
    FOREIGN KEY (`provincia_id`)
    REFERENCES `MOP`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `MOP`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `producto_id`
    FOREIGN KEY (`producto_id`)
    REFERENCES `MOP`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `provincia_id_idx` ON `MOP`.`Solicitud` (`provincia_id` ASC);

CREATE INDEX `usuario_id_idx` ON `MOP`.`Solicitud` (`usuario_id` ASC) ;

CREATE INDEX `producto_id_idx` ON `MOP`.`Solicitud` (`producto_id` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
