-- MySQL Script generated by MySQL Workbench
-- Wed Dec 21 16:13:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MOP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MOP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MOP` DEFAULT CHARACTER SET utf8 ;
USE `MOP` ;

-- -----------------------------------------------------
-- Table `MOP`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MOP`.`Proveedor` (
  `idProveedor` INT NOT NULL,
  `rut_proveedor` VARCHAR(45) NOT NULL,
  `nombre_proveedor` VARCHAR(45) NOT NULL,
  `telefono_proveedor` VARCHAR(45) NOT NULL,
  `direccion_proveedor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProveedor`));


-- -----------------------------------------------------
-- Table `MOP`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MOP`.`Factura` (
  `idFactura` INT NOT NULL,
  `nro_factura` VARCHAR(45) NOT NULL,
  `orden_compra` VARCHAR(45) NOT NULL,
  `fecha_factura` DATE NOT NULL,
  `proveedor_id` INT NOT NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `proveedor_id_idx` (`proveedor_id` ASC),
  CONSTRAINT `proveedor_id`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `MOP`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `MOP`.`Tipo_medida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MOP`.`Tipo_medida` (
  `idTipo_medida` INT NOT NULL,
  `descripcion_medida` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo_medida`));


-- -----------------------------------------------------
-- Table `MOP`.`Bodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MOP`.`Bodega` (
  `idBodega` INT NOT NULL,
  `nombre_bodega` VARCHAR(45) NOT NULL,
  `direccion_bodega` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idBodega`));


-- -----------------------------------------------------
-- Table `MOP`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MOP`.`Producto` (
  `idProducto` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `cantidad` INT NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
  `tipo_medida_id` INT NOT NULL,
  `factura_id` INT NOT NULL,
  `bodega_id` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `tipo_medida_id_idx` (`tipo_medida_id` ASC),
  INDEX `factura_id_idx` (`factura_id` ASC),
  INDEX `bodega_id_idx` (`bodega_id` ASC),
  CONSTRAINT `tipo_medida_id`
    FOREIGN KEY (`tipo_medida_id`)
    REFERENCES `MOP`.`Tipo_medida` (`idTipo_medida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `factura_id`
    FOREIGN KEY (`factura_id`)
    REFERENCES `MOP`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bodega_id`
    FOREIGN KEY (`bodega_id`)
    REFERENCES `MOP`.`Bodega` (`idBodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `MOP`.`Perfil_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MOP`.`Perfil_usuario` (
  `idPerfil_usuario` INT NOT NULL,
  `descripcion_perfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPerfil_usuario`));


-- -----------------------------------------------------
-- Table `MOP`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MOP`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `contrasenha` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `run` VARCHAR(45) NOT NULL,
  `bodegaid` INT NOT NULL,
  `perfil_id` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `perfil_id_idx` (`perfil_id` ASC),
  INDEX `bodega_id_idx` (`bodegaid` ASC),
  CONSTRAINT `bodegaid`
    FOREIGN KEY (`bodegaid`)
    REFERENCES `MOP`.`Bodega` (`idBodega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `perfil_id`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `MOP`.`Perfil_usuario` (`idPerfil_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `MOP`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MOP`.`Provincia` (
  `idProvincia` INT NOT NULL,
  `nombre_provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProvincia`));


-- -----------------------------------------------------
-- Table `MOP`.`Solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MOP`.`Solicitud` (
  `idSolicitud` INT NOT NULL,
  `nro_solicitud` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `run` VARCHAR(45) NOT NULL,
  `fecha_solicitud` DATE NOT NULL,
  `provincia_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`idSolicitud`),
  INDEX `provincia_id_idx` (`provincia_id` ASC),
  INDEX `usuario_id_idx` (`usuario_id` ASC),
  CONSTRAINT `provincia_id`
    FOREIGN KEY (`provincia_id`)
    REFERENCES `MOP`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `MOP`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `MOP`.`Detalle_solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MOP`.`Detalle_solicitud` (
  `idDetalle_solicitud` INT NOT NULL,
  `productoid` INT NOT NULL,
  `solicitudid` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`idDetalle_solicitud`),
  INDEX `productoid_idx` (`productoid` ASC),
  INDEX `solicitudid_idx` (`solicitudid` ASC),
  CONSTRAINT `productoid`
    FOREIGN KEY (`productoid`)
    REFERENCES `MOP`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `solicitudid`
    FOREIGN KEY (`solicitudid`)
    REFERENCES `MOP`.`Solicitud` (`idSolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
